### ISSUE TITLE
WLC Template

### ISSUE THREAD

**Issue by zenemichels** [rconfig/rConfig-templates#15]
I see previous issues about the Cisco WLC template not working and closed out. I wanted to see if there was anymore work done on the template so that it is functional?

**Comment by rconfig** [comment]
not at this time, and due to lack of demand, i will not reopen in near future

**Comment by cattamite** [comment]
I would +1 the WLC Template.  I was playing with it alot and couldnt get it to work on SSH or Telnet.  This is still an active product for Cisco and it would be great if this awesome tool supported it.  Then all of my Cisco devices would be happy.  I shoe-horned the config in manually by editing the text file, since like the other user all the configs show as blank.
