### ISSUE TITLE
Fortigate 

### ISSUE THREAD

**Issue by rhofran** [rconfig/rConfig-templates#25]
Hi,

I installed recently rConfig to backup my cisco switches and Fortigate firewalls.
It works for Cisco Switches, but not for fortigate firewalls. Even If I download the template : fortigate-ssh-noenable.yml, no chance.
Does this product work for fortigates?

Can you please help me? 

Thanks

**Comment by martinparr** [comment]
There are a couple of additional steps required.

1. Add a new category; 'Fortigate' as an example
2. Add a new command; 'show' and associate with the newly created category in step 1.
3. Update the device to use the new category type

This is because Fortigate doesn't like 'show startup-config'

**Comment by gloverm19** [comment]
Thanks for the previous response but this still doesn't work.

**Comment by simodepa97** [comment]
I followed the steps but it still doesn't work.

The file you create is empty inside.

How could I solve?

**Comment by misterbux** [comment]
> I followed the steps but it still doesn't work.
> 
> The file you create is empty inside.
> 
> How could I solve?

I have a same issue, anyone can help? Thanks.

**Comment by TOAOQ** [comment]
For the people where it doesn't work: do you use VDOMS?
I have Fortigates running without VDOMS and it works, and one stack with VDOMS and it doesn't work. Reason is you first have to get into the designated management VDOM before you are able to use the command show full-config.
Stil figuring out how to either connect directly into management VDOM instead of global, or parse multiple lines of commands in order to rertrieve the config.
